#!/usr/bin/env python
import subprocess

from hexes import (
    Application,
    Box,
    Style,
)
from hexes.behaviors import quit

# Layout
root = Box(
    style=Style(
        layout=Style.Layout.Horizontal,
    ),
    children=(
        Box(
            children=(
                Box(),
                Box(
                    style=Style(
                        height=3,
                    ),
                ),
            ),
        ),
        Box(
            style=Style(
                width=20,
            ),
        ),
    ),
)

# Logic
app = Application(root=root)
app.register('q', quit)


@app.on('ready')
def show_files(app):
    ls = str(subprocess.check_output('ls'), 'utf-8')
    if app.root.children[0].children[0].text != ls:
        app.log("ls")
        app.root.children[0].children[0].text = ls
    app.loop.create_task(show_files(app))


# Run
with app:
    app.run()
